### ISSUE TITLE
How is fclone useful?

### ISSUE THREAD

**Issue by geirman** [soyuka/fclone#3]
What are the use cases where this becomes useful?

**Comment by soyuka** [comment]
Say you've a circular object in javascript that you want to serialize: 

```
> let a = {foo: 'bar'}
> a.b = a
{ foo: 'bar', b: [Circular] }
> JSON.stringify(a)
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:224:10)
    at REPLServer.Interface._line (readline.js:566:8)
```

Now, by using `fclone` you can clone that object, and get rid of circular references:

```
> const fclone = require('./dist/fclone.js')
> let a = {foo: 'bar'}
> a.b = a
{ foo: 'bar', b: [Circular] }
> console.log(JSON.stringify(fclone(a)))
{"b":"[Circular]","foo":"bar"}
```

There are plenty modules that are achieving the same goal:
- jsan 
- circularjson 
- deepcopy 
- json-stringify-safe 
- safe-clone-deep (this code was based on it's workflow btw)

If you find others please let me know so that I add them to the bench.

Cheers

**Comment by geirman** [comment]
that is pretty clear, thanks! I guess I've never had a use case that required a circular object.

**Comment by tracker1** [comment]
@geirman the most common one I've seen is if you try to log the response or request object for http requests with express, it gets pretty messy.  I write safe-clone-deep for this case, but I think fclone is a little better, and may steal a couple parts.  Works well with json-stable-stringify if you want to do diffs as well.

**Comment by soyuka** [comment]
@tracker1 indeed, we use this mainly to clone a `child_process` where there is a circular reference we want to get rid off. `safe-clone-deep` had issues on node 6 from what I can remember and we wanted it to still be compatible with node 0.10 ([deep-clone](https://github.com/thebearingedge/deep-clone) uses es6 map, which is a great choice to handle circular values).

**Comment by geirman** [comment]
Ah, I haven't done much with express at all. Thanks for the education. Good to know this exists and why. Also interesting to hear the pros/cons of different approaches
